create module heart
libreconnect/backend pull request #3
Opened 2024-07-15 18:07 UTC by je-suis-professionnelle

2024-07-15 18:08 UTC, je-suis-professionnelle commented
probleme de format de date, avec vine je peux utiliser que date, pas datetime, ce qui faisait une incompatibilité avec le type DateTime dans le model Heart, j'ai donc tout passé en Date mais je ne suis pas sûre qu'il faille faire ça

2024-07-15 18:16 UTC, NathaelB requested changes
The code as a whole is clean, you've separated the behaviours in the controller and in the service. When creating a resource, you manage errors by raising exceptions and handling them correctly, which is great.

I've commented on certain parts to take into account the parameters passed to a request.

Once the authorisation system has been established, we can add this part later!

Excellent work!

2024-07-15 18:16 UTC, NathaelB commented on apps/heart/validators/heart.ts
> +export const HeartQueryValidator = vine.compile(
You can rename it to `heartQueryValidator` and create a interface `HeartQuerySchema`

2024-07-15 18:16 UTC, NathaelB commented on apps/heart/controllers/patient_heart_rates_controller.ts
> +    return this.heartService.findByPatientId(data.patientId)
You've defined the `patientId` as optional, so if it's undefined you'll have a problem.
In the controller behaviour, if the patientId is defined then it's often a professional who will check the data. If no patientId is provided, we use the identifier of the connected patient.

2024-07-15 18:16 UTC, NathaelB commented on apps/heart/services/patient_heart_rates_service.ts
> +  async findByPatientId(patientId: string) {
Your validator takes several parameters, but they're not used here, is that normal?

2024-07-16 15:51 UTC, je-suis-professionnelle commented on apps/heart/controllers/patient_heart_rates_controller.ts
> +    return this.heartService.findByPatientId(data.patientId)
"we use the identifier of the connected patient." how should i get it ?

2024-07-18 08:15 UTC, Courtcircuits commented on apps/heart/services/patient_heart_rates_service.ts
> +        code: 'E_HEART_CREATE',
Rename this into `E_HEART_RATE_CREATE`

2024-07-18 08:22 UTC, je-suis-professionnelle commented on apps/heart/services/patient_heart_rates_service.ts
> +        code: 'E_HEART_CREATE',
yes yes

2024-07-20 16:44 UTC, NathaelB requested changes

2024-07-20 16:44 UTC, NathaelB commented on apps/shared/models/heart.ts
In the validator to manage a patient's heart rate, it was specified to have an array like this:

```json
{
  "patientId": "123456",
  "heartRates": [
    {
      "startDate": "2024-06-30T19:42:00Z",
      "endDate": "2024-06-30T19:42:00Z",
      "heartRate": 100,
    },
  ]
}
```

Looking around, here you've created a `heart` model that represents heart rate? If so, there are a few problems:
- The name is too general, `heart_rate` would be more appropriate
- Why model ranges for the time and value metrics?

2024-07-20 16:44 UTC, NathaelB commented on apps/heart/validators/heart.ts
Heart represents the entire module, as a kind of service.

Here in the issue we were asked to manage the heart rate part. So heart_rate would be more appropriate.
Note that the `createHeartValidator` does not respect the contract established in the issue.

<img width="904" alt="image" src="https://github.com/user-attachments/assets/19d98688-cc2f-4e27-bc10-a0725fff9beb">

2024-07-20 16:44 UTC, NathaelB commented on apps/heart/controllers/patient_heart_rates_controller.ts
I've modified the controller to show you an example of API documentation.
I've also changed the name of the service: `heartService` -> `patientHeartRatesService`

2024-07-26 12:25 UTC, NathaelB approved these changes

2024-07-26 12:25 UTC, merged